### ISSUE TITLE
Enabling Adaptive High Beam (not automatic high beam) on USDM cars (ECU Hack)?

### ISSUE THREAD

**Issue by zorrobyte** [sparkiedk/Toyota-PCM-hacking#2]
For USDM BMWs, there is an ECU hack to enable AHS: https://f15.bimmerpost.com/forums/attachment.php?attachmentid=1344101&d=1452268635

I also just bought a Carista to hack my Prius to turn off the awful reverse beep. Sometime soon, I'll be building an Openpilot system for lane-keeping autonomy.

Our USDM Priuses with LED headlights have the hardware to enable AHS, the question is, how can we hack our ECUs to enable it?

While I'm both a Software Engineer and have an ASE cert (I've dropped engines and turned around and wrote software the evening after), I'm lost as I've never owned a modern Toyota. The only other ECU hacking experience I have so far is socking my ECU in the 1987 CRX to burn AFR maps. Arduino and Pi skills be damned.

So forgive me for some of these (likely) basic questions
How does one view/modify option codes in the Prius ECU?
Are such modifications via the CAN bus, or is some sort of JTAG to the ECU necessary?
Has anyone been able to change option codes/ECU code on a modern Toyota yet?
Any other car hackers want to team up?

**Comment by sparkiedk** [comment]
My apologies for ignoring this for so long, blame github's stupid capcha dice.

This seems far beyond the scope of hacking the older pcm's, and certainly beyond my expertise. I will close for now, but if you have data and methods for breaking into newer computers I would certainly entertain hosting them in this repo or one like it.
